### ISSUE TITLE
Update nps & nps-utils

### ISSUE THREAD

**Issue by scottnath** [Mehuge/nps-plus#4]
- `nps-plus` version: 1.0.3
- `node` version: 10.16
- `npm` version: 6.9
- nps current version: 5.9.5
- nps-utils current version: 1.7.0

According to nps-plus package.json.dependencies, versions of `nps` and `nps-utils` are behind the current versions. Is it possible to get nps-plus updated to the latest versions of both of these modules?

thanks,
Scott

**Comment by Mehuge** [comment]
commit 22fa25769b35a88e94329b5def10579ca54236c4 updates nps to 5.9.5 and nps-utils to 1.7.0 and fixes a number of `npm audit` reported vulnerabilities.

Published to https://www.npmjs.com/package/nps-plus as version 1.0.6

**Comment by scottnath** [comment]
fantastic! thank you @Mehuge
